image: docker:stable

services:
  - docker:dind

stages:
  - test

variables:
  DOCKER_DRIVER: overlay2

lint-user-side:
  stage: test
  image: node:12.2.0
  only:
    changes:
      - user-side/**/*
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - user-side/node_modules
  before_script:
    - cd user-side
    - npm i --loglevel error
  script:
    - npm run lint:ci

test-user-side:
  stage: test
  image: node:12.2.0
  only:
    changes:
      - user-side/**/*
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - user-side/node_modules
  image: node
  before_script:
    - cd user-side
    - npm i --loglevel error
  script:
    - npm test

