env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:vue/essential'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  parser: '@typescript-eslint/parser'
plugins:
  - 'vue'
  - 'import'
  - '@typescript-eslint'
settings:
  "import/parsers":
    "@typescript-eslint/parser": [ .ts, .tsx ]
rules:
  "no-console": "warn"
  "quotes": 
    - "error"
    - "single"
  "@typescript-eslint/no-unused-vars": "error"
  "@typescript-eslint/no-use-before-define": 0
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/no-explicit-any": 0
  "vue/order-in-components": "error"
  "vue/html-indent": 
    - "error"
    - "tab"
  "vue/script-indent":
    - "error"
    - "tab"